"""empty message

Revision ID: 0e3e2c72439a
Revises: c4529604f491
Create Date: 2024-09-02 17:19:01.968889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e3e2c72439a'
down_revision = 'c4529604f491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeslots', schema=None) as batch_op:
        batch_op.drop_index('ix_timeslots_date')
        batch_op.drop_index('ix_timeslots_doctor_id')
        batch_op.drop_index('ix_timeslots_end_time')
        batch_op.drop_index('ix_timeslots_id')
        batch_op.drop_index('ix_timeslots_start_time')
        batch_op.drop_index('ix_timeslots_status')

    op.drop_table('timeslots')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeslots',
    sa.Column('doctor_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('start_time', sa.TIME(), nullable=False),
    sa.Column('end_time', sa.TIME(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('end_time > start_time', name='check_time_validity'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'date', 'start_time', name='doctor_date_startTime_uc')
    )
    with op.batch_alter_table('timeslots', schema=None) as batch_op:
        batch_op.create_index('ix_timeslots_status', ['status'], unique=False)
        batch_op.create_index('ix_timeslots_start_time', ['start_time'], unique=False)
        batch_op.create_index('ix_timeslots_id', ['id'], unique=False)
        batch_op.create_index('ix_timeslots_end_time', ['end_time'], unique=False)
        batch_op.create_index('ix_timeslots_doctor_id', ['doctor_id'], unique=False)
        batch_op.create_index('ix_timeslots_date', ['date'], unique=False)

    # ### end Alembic commands ###
