# flake8: noqa
"""empty message

Revision ID: 4ec865f9726a
Revises: c6e8f995b720
Create Date: 2024-09-11 17:50:58.203984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ec865f9726a"
down_revision = "c6e8f995b720"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receptionists",
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("receptionists", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_receptionists_email"), ["email"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_receptionists_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_receptionists_name"), ["name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_receptionists_phone"), ["phone"], unique=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("receptionists", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_receptionists_phone"))
        batch_op.drop_index(batch_op.f("ix_receptionists_name"))
        batch_op.drop_index(batch_op.f("ix_receptionists_id"))
        batch_op.drop_index(batch_op.f("ix_receptionists_email"))

    op.drop_table("receptionists")
    # ### end Alembic commands ###
