# flake8: noqa
"""Edited Patient Table

Revision ID: a4490feccc89
Revises: 83d326736d96
Create Date: 2024-08-24 21:21:38.568053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4490feccc89'
down_revision = '83d326736d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('medical_history',
               existing_type=sa.VARCHAR(length=400),
               nullable=True)
        batch_op.alter_column('current_medications',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('department_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('department_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('current_medications',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('medical_history',
               existing_type=sa.VARCHAR(length=400),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
