"""empty message

Revision ID: b5521f990fc4
Revises: f0c6347135e6
Create Date: 2024-09-08 18:54:28.140818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5521f990fc4'
down_revision = 'f0c6347135e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###
