"""empty message

Revision ID: c6e8f995b720
Revises: f001a3e7c45a
Create Date: 2024-09-09 21:28:25.557492

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c6e8f995b720"
down_revision = "f001a3e7c45a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vitals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("measured_at", sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("vitals", schema=None) as batch_op:
        batch_op.drop_column("measured_at")

    # ### end Alembic commands ###
