# flake8: noqa
"""initial migration

Revision ID: e1ce2f145566
Revises:
Create Date: 2024-08-23 15:21:03.519984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ce2f145566'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('medical_history', sa.String(length=400), nullable=False),
    sa.Column('current_medications', sa.String(length=256), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_contact_number'), ['contact_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_name'))
        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.drop_index(batch_op.f('ix_patients_email'))
        batch_op.drop_index(batch_op.f('ix_patients_contact_number'))

    op.drop_table('patients')
    # ### end Alembic commands ###
