# flake8: noqa

"""empty message

Revision ID: ebd01299b571
Revises: 71b138a91fce
Create Date: 2024-08-28 13:45:54.953926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd01299b571'
down_revision = '71b138a91fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admins_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_admins_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_admins_phone'), ['phone'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admins_phone'))
        batch_op.drop_index(batch_op.f('ix_admins_name'))
        batch_op.drop_index(batch_op.f('ix_admins_id'))

    op.drop_table('admins')
    # ### end Alembic commands ###
