# flake8: noqa
"""empty message

Revision ID: f0c6347135e6
Revises:
Create Date: 2024-09-02 17:42:14.441015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0c6347135e6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_admins_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_admins_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_admins_phone"), ["phone"], unique=True)

    op.create_table(
        "departments",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_departments_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_departments_name"), ["name"], unique=False)

    op.create_table(
        "doctors",
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("certificates", sa.String(length=256), nullable=False),
        sa.Column("department_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("phone", sa.String(length=10), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doctors_department_id"), ["department_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_doctors_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_doctors_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_doctors_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_doctors_phone"), ["phone"], unique=True)

    op.create_table(
        "patients",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("contact_number", sa.String(length=10), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column("password_hash", sa.String(length=256), nullable=False),
        sa.Column("address", sa.String(length=256), nullable=True),
        sa.Column("medical_history", sa.String(length=400), nullable=True),
        sa.Column("current_medications", sa.String(length=256), nullable=True),
        sa.Column("department_id", sa.String(length=128), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("national_id", sa.String(length=10), nullable=False),
        sa.Column(
            "gender", sa.Enum("Male", "Female", name="gendertype"), nullable=False
        ),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("national_id"),
    )
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_patients_contact_number"), ["contact_number"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_patients_email"), ["email"], unique=True)
        batch_op.create_index(batch_op.f("ix_patients_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_patients_name"), ["name"], unique=False)

    op.create_table(
        "allergies",
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("allergen", sa.String(length=256), nullable=True),
        sa.Column("reaction", sa.String(length=256), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_id", "allergen", name="uq_patient_allergy"),
    )
    with op.batch_alter_table("allergies", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_allergies_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_allergies_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "appointments",
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("doctor_id", sa.String(length=128), nullable=False),
        sa.Column("appointment_time", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SCHEDULED", "COMPLETED", "CANCELLED", name="appointmentstatus"),
            nullable=False,
        ),
        sa.Column("reason", sa.String(length=256), nullable=True),
        sa.Column("notes", sa.String(length=256), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_appointments_appointment_time"),
            ["appointment_time"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_appointments_doctor_id"), ["doctor_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_appointments_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_appointments_patient_id"), ["patient_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_appointments_status"), ["status"], unique=False
        )

    op.create_table(
        "diagnoses",
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("diagnose_name", sa.String(length=256), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("patient_id", "diagnose_name", name="uq_patient_diagnose"),
    )
    with op.batch_alter_table("diagnoses", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_diagnoses_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_diagnoses_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "prescriptions",
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("medication", sa.String(length=50), nullable=True),
        sa.Column("dosage", sa.String(length=50), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prescriptions_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_prescriptions_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "vitals",
        sa.Column("patient_id", sa.String(length=128), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("temperature", sa.Float(), nullable=False),
        sa.Column("blood_pressure", sa.String(length=10), nullable=False),
        sa.Column("pulse", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("vitals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_vitals_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_vitals_patient_id"), ["patient_id"], unique=False
        )

    op.create_table(
        "working_hours",
        sa.Column("doctor_id", sa.String(length=128), nullable=False),
        sa.Column("start_time", sa.Time(), nullable=False),
        sa.Column("end_time", sa.Time(), nullable=False),
        sa.Column(
            "day",
            sa.Enum(
                "SUNDAY",
                "MONDAY",
                "TUESDAY",
                "WEDNESDAY",
                "THURSDAY",
                "FRIDAY",
                "SATURDAY",
                name="dayofweek",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint("end_time > start_time", name="check_time_validity"),
        sa.ForeignKeyConstraint(
            ["doctor_id"],
            ["doctors.id"],
        ),
        sa.PrimaryKeyConstraint("doctor_id", "day"),
    )
    with op.batch_alter_table("working_hours", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_working_hours_day"), ["day"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_working_hours_doctor_id"), ["doctor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_working_hours_end_time"), ["end_time"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_working_hours_start_time"), ["start_time"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("working_hours", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_working_hours_start_time"))
        batch_op.drop_index(batch_op.f("ix_working_hours_end_time"))
        batch_op.drop_index(batch_op.f("ix_working_hours_doctor_id"))
        batch_op.drop_index(batch_op.f("ix_working_hours_day"))

    op.drop_table("working_hours")
    with op.batch_alter_table("vitals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_vitals_patient_id"))
        batch_op.drop_index(batch_op.f("ix_vitals_id"))

    op.drop_table("vitals")
    with op.batch_alter_table("prescriptions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prescriptions_patient_id"))
        batch_op.drop_index(batch_op.f("ix_prescriptions_id"))

    op.drop_table("prescriptions")
    with op.batch_alter_table("diagnoses", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_diagnoses_patient_id"))
        batch_op.drop_index(batch_op.f("ix_diagnoses_id"))

    op.drop_table("diagnoses")
    with op.batch_alter_table("appointments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_appointments_status"))
        batch_op.drop_index(batch_op.f("ix_appointments_patient_id"))
        batch_op.drop_index(batch_op.f("ix_appointments_id"))
        batch_op.drop_index(batch_op.f("ix_appointments_doctor_id"))
        batch_op.drop_index(batch_op.f("ix_appointments_appointment_time"))

    op.drop_table("appointments")
    with op.batch_alter_table("allergies", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allergies_patient_id"))
        batch_op.drop_index(batch_op.f("ix_allergies_id"))

    op.drop_table("allergies")
    with op.batch_alter_table("patients", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_patients_name"))
        batch_op.drop_index(batch_op.f("ix_patients_id"))
        batch_op.drop_index(batch_op.f("ix_patients_email"))
        batch_op.drop_index(batch_op.f("ix_patients_contact_number"))

    op.drop_table("patients")
    with op.batch_alter_table("doctors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doctors_phone"))
        batch_op.drop_index(batch_op.f("ix_doctors_name"))
        batch_op.drop_index(batch_op.f("ix_doctors_id"))
        batch_op.drop_index(batch_op.f("ix_doctors_email"))
        batch_op.drop_index(batch_op.f("ix_doctors_department_id"))

    op.drop_table("doctors")
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_departments_name"))
        batch_op.drop_index(batch_op.f("ix_departments_id"))

    op.drop_table("departments")
    with op.batch_alter_table("admins", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_admins_phone"))
        batch_op.drop_index(batch_op.f("ix_admins_name"))
        batch_op.drop_index(batch_op.f("ix_admins_id"))

    op.drop_table("admins")
    # ### end Alembic commands ###
